Copycat-dmmwebcamp/naganocake

app/controllers/End_user/registrations_controller.rb
app/views/admins/registrations/new.html.erb
app/views/end_users/registrations/new.html.erb
config/initializers/devise.rb
config/routes.rb
db/migrate/20200515053304_remove_user_status_from_end_users.rb
db/migrate/20200515053429_add_user_status_to_end_users.rb
db/schema.rb

エンドユーザー側のログイン画面を作成
エンドユーザのテーブル作成
ログインできることは確認済み

add login-function

---

app/controllers/admins/categories_controller.rb
app/controllers/admins/homes_controller.rb
app/views/admins/categories/edit.html.erb
app/views/admins/categories/index.html.erb
app/views/admins/homes/top.html.erb
db/migrate/20200516120623_remove_password_from_end_users.rb
db/migrate/20200516120919_remove_end_user_id_from_orders.rb
db/migrate/20200516121113_add_end_user_to_orders.rb
db/schema.rb

N make admins top and category 2

---

Gemfile
Gemfile.lock
app/controllers/admins/items_controller.rb
app/controllers/application_controller.rb
app/controllers/end_users/registrations_controller.rb
app/models/item.rb
app/views/admins/items/edit.html.erb
app/views/admins/items/index.html.erb
app/views/admins/items/new.html.erb
app/views/admins/items/show.html.erb
db/migrate/20200516080818_remove_item_image_from_items.rb
db/migrate/20200516080924_add_item_image_id_to_items.rb
db/schema.rb
db/seeds.rb

A admins item

---

app/controllers/admins/items_controller.rb
app/controllers/end_users/items_controller.rb
app/views/admins/categories/index.html.erb
app/views/admins/items/edit.html.erb
app/views/admins/items/index.html.erb
app/views/admins/items/new.html.erb
app/views/admins/items/show.html.erb
app/views/admins/registrations/new.html.erb
app/views/end_users/items/_categories.html.erb
app/views/end_users/items/index.html.erb
app/views/end_users/items/show.html.erb
app/views/end_users/items/top.html.erb
config/routes.rb
db/migrate/20200516124305_add_end_user_to_orders.rb
db/schema.rb
db/seeds.rb

エンドユーザ側のログイン調整
エンドユーザー側の商品関連とトップページの作成

A end user items

---

app/controllers/end_users/orders_controller.rb
app/models/delivery_place.rb
app/models/end_user.rb
app/views/end_users/orders/index.html.erb
app/views/end_users/orders/new.html.erb
config/locales/ja.yml
config/routes.rb

A end user order

---

app/controllers/end_users/carts_controller.rb
app/controllers/end_users/items_controller.rb
app/views/end_users/carts/index.html.erb
app/views/end_users/items/show.html.erb
app/views/end_users/items/top.html.erb

カート画面を作成しました。
　→destroy_allのアクションは作成しましたが、ルーティングはまだです。
アイテム詳細画面にカートに入れるボタンを作りました。

K make cart

---

app/views/end_users/registrations/new.html.erb
app/views/end_users/sessions/new.html.erb
app/views/end_users/shared/_links.html.erb
app/views/end_users/users/edit.html.erb
app/views/end_users/users/index.html.erb

エンドユーザー側の新規会員登録、ログイン画面、会員情報編集画面のレイアウトを一部修正。
ログイン画面は３割程度しかできていないので再度修正が必要です。

G bootstrap

---

app/controllers/end_users/items_controller.rb
app/controllers/end_users/orders_controller.rb
app/views/end_users/items/show.html.erb
app/views/end_users/orders/complete.html.erb
app/views/end_users/orders/index.html.erb
app/views/end_users/orders/new.html.erb
config/routes.rb
db/migrate/20200516124305_add_end_user_to_orders.rb

A end user order confirm

---

app/views/end_users/orders/history.html.erb
app/views/end_users/orders/history_show.html.erb

注文履歴のページを作成しました。
コントローラーにはまだ記述を追加していません。

K make order history

---

app/controllers/admins/items_controller.rb
app/models/category.rb
app/models/item.rb
app/views/admins/items/_error_messages.html.erb
app/views/admins/items/new.html.erb

管理者側のitemとcategoryにバリデーションを追加しました。
エラー文の表示は現在作成中です。

validation2

---

app/controllers/admins/order_histories_controller.rb
app/controllers/end_users/orders_controller.rb
app/models/order.rb
app/views/admins/order_histories/index.html.erb
app/views/admins/order_histories/show.html.erb
app/views/admins/order_histories/update_order.html.erb
app/views/end_users/users/new.html.erb
config/routes.rb

管理者側の商品履歴一覧・詳細ページ製作
作動確認OK
郵便番号のケタ分けはまだ

G admin order history2

---

app/controllers/end_users/orders_controller.rb
app/views/end_users/carts/index.html.erb
app/views/end_users/orders/history_show.html.erb
app/views/end_users/orders/show.html.erb
app/views/end_users/users/new.html.erb
db/schema.rb

K fix order history

---

app/controllers/admins/categories_controller.rb
app/controllers/admins/items_controller.rb
app/controllers/admins/users_controller.rb
app/controllers/end_users/carts_controller.rb
app/controllers/end_users/deliveries_controller.rb
app/controllers/end_users/users_controller.rb
app/models/admin.rb
app/models/cart_item.rb
app/models/category.rb
app/models/delivery_place.rb
app/models/end_user.rb
app/models/item.rb
app/models/order.rb
app/models/order_item.rb
app/views/admins/categories/edit.html.erb
app/views/admins/categories/index.html.erb
app/views/admins/items/edit.html.erb
app/views/admins/items/new.html.erb
app/views/admins/shared/_error_messages.html.erb
app/views/admins/users/edit.html.erb
app/views/end_users/carts/index.html.erb
app/views/end_users/deliveries/edit.html.erb
app/views/end_users/deliveries/index.html.erb
app/views/end_users/orders/index.html.erb
app/views/end_users/registrations/new.html.erb
app/views/end_users/sessions/new.html.erb
app/views/end_users/shared/_error_messages.html.erb
app/views/end_users/users/edit.html.erb
config/locales/ja.yml

バリデーションを各モデルに追加しました。
エラー文も合わせて表示させるように変更しています。
管理者・ユーザー側どちらもログイン画面にはまだバリデーションを加えていません。

N validation3

---

app/controllers/application_controller.rb
app/views/admins/registrations/new.html.erb
app/views/admins/sessions/new.html.erb
app/views/admins/shared/_links.html.erb
app/views/end_users/sessions/new.html.erb
app/views/end_users/shared/_links.html.erb
config/locales/ja.yml

新規登録画面、ログイン画面のvalidationとエラー文を追記しました。
エラー文の日本語も合わせて記入しています。

N validation4

---

app/controllers/admins/homes_controller.rb
app/controllers/admins/items_controller.rb
app/controllers/admins/order_histories_controller.rb
app/controllers/application_controller.rb
app/controllers/end_users/orders_controller.rb
app/models/delivery_place.rb
app/views/admins/items/index.html.erb
app/views/admins/items/show.html.erb
app/views/end_users/items/index.html.erb
app/views/end_users/items/show.html.erb
app/views/end_users/items/top.html.erb
app/views/end_users/sessions/new.html.erb
app/views/end_users/users/leave.html.erb

商品の削除機能の追加
退会時の確認画面の調整
ログアウト後のリダイレクト先の変更

A admin item delete

---

app/controllers/end_users/orders_controller.rb
app/views/admins/order_histories/show.html.erb
app/views/end_users/carts/index.html.erb
app/views/end_users/items/index.html.erb
app/views/end_users/items/show.html.erb
app/views/end_users/items/top.html.erb
app/views/end_users/orders/index.html.erb

K add comma

---

app/assets/stylesheets/application.scss
app/views/admins/registrations/new.html.erb
app/views/layouts/application.html.erb
config/locales/ja.yml

日本語になっていないバリデーションを修正しました。
ヘッダー上にroot_pathをつけました。

Fix validation link

---

Gemfile
Gemfile.lock
app/controllers/admins/items_controller.rb
app/controllers/admins/order_histories_controller.rb
app/controllers/admins/users_controller.rb
app/controllers/end_users/items_controller.rb
app/views/admins/items/index.html.erb
app/views/admins/order_histories/index.html.erb
app/views/admins/users/index.html.erb
app/views/end_users/items/index.html.erb
app/views/end_users/items/top.html.erb
app/views/kaminari/_first_page.html.erb
app/views/kaminari/_gap.html.erb
app/views/kaminari/_last_page.html.erb
app/views/kaminari/_next_page.html.erb
app/views/kaminari/_page.html.erb
app/views/kaminari/_paginator.html.erb
app/views/kaminari/_prev_page.html.erb
config/initializers/kaminari_config.rb

エンドユーザー側の商品一覧、admin側の商品一覧、会員一覧、注文履歴一覧にkaminariを追加
topページ下部に『もっと見る>』を追加

G kaminari

---

app/assets/javascripts/admins/searches.coffee
app/assets/stylesheets/admins/searches.scss
app/controllers/admins/order_histories_controller.rb
app/controllers/admins/searches_controller.rb
app/helpers/admins/searches_helper.rb
app/models/end_user.rb
app/models/item.rb
app/views/admins/searches/search.html.erb
app/views/admins/users/show.html.erb
app/views/layouts/application.html.erb
config/routes.rb
test/controllers/admins/searches_controller_test.rb

A admin search

---

app/assets/stylesheets/admins/categories.scss
app/assets/stylesheets/admins/homes.scss
app/assets/stylesheets/admins/items.scss
app/assets/stylesheets/admins/order_histories.scss
app/assets/stylesheets/admins/users.scss
app/assets/stylesheets/end_users/users.scss
app/views/admins/categories/edit.html.erb
app/views/admins/categories/index.html.erb
app/views/admins/homes/top.html.erb
app/views/admins/items/index.html.erb
app/views/admins/order_histories/index.html.erb
app/views/admins/registrations/new.html.erb
app/views/admins/sessions/new.html.erb
app/views/admins/users/index.html.erb
app/views/end_users/registrations/new.html.erb
app/views/end_users/sessions/new.html.erb
config/locales/ja.yml

管理者側：ログイン・新規登録、商品一覧、会員一覧、ジャンル一覧、注文履歴一覧・詳細
ユーザー側：ログイン・新規登録
上記画面のデザインを行いました。

N design 2

---

app/assets/stylesheets/admins/categories.scss
app/assets/stylesheets/admins/order_histories.scss
app/assets/stylesheets/admins/users.scss
app/assets/stylesheets/end_users/orders.scss
app/assets/stylesheets/end_users/users.scss
app/controllers/admins/order_histories_controller.rb
app/views/admins/categories/edit.html.erb
app/views/admins/categories/index.html.erb
app/views/admins/items/new.html.erb
app/views/admins/sessions/new.html.erb
app/views/admins/users/edit.html.erb
app/views/admins/users/show.html.erb
app/views/end_users/carts/index.html.erb
app/views/end_users/deliveries/index.html.erb
app/views/end_users/orders/history_show.html.erb
app/views/end_users/orders/index.html.erb
app/views/end_users/orders/new.html.erb
app/views/end_users/registrations/new.html.erb
app/views/end_users/sessions/new.html.erb
app/views/end_users/users/edit.html.erb
app/views/end_users/users/leave.html.erb
app/views/end_users/users/new.html.erb
app/views/layouts/application.html.erb

デザインの微調整を行っています。
admin、end_userどちらも全体的に修正しています。

N design fix

---

app/controllers/end_users/carts_controller.rb
app/views/end_users/carts/_cart_item.html.erb
app/views/end_users/carts/index.html.erb
app/views/end_users/carts/update.js.erb

fix cart add ajax

---

app/assets/stylesheets/application.scss
app/views/admins/items/index.html.erb
app/views/layouts/application.html.erb
config/locales/ja.yml

管理者側の＋マークを修正しました。
ロゴの下線を表示されないように修正しました。

K fix image
